# Generated by Django 3.2.5 on 2021-07-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('name', models.CharField(default='', max_length=20, unique=True)),
                ('team', models.CharField(default='alone', max_length=20)),
                ('keyword', models.CharField(default='', max_length=20)),
                ('details', models.CharField(default='None', max_length=50)),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
